@extends('layouts.user')
@section('content')
<div class="page-heading"><div><div class="eyebrow">MEMBER WORKSPACE</div><h1>マイページ</h1></div><div class="page-actions"><a class="btn secondary" href="{{ route('notifications.index') }}">通知 {{ $unreadNotificationCount }}</a><a class="btn secondary" href="{{ route('inquiries.index') }}">問い合わせ {{ $inquiryCount }}</a></div></div>
<section class="dashboard-summary">
    <div class="summary-main"><span class="meta">ACCOUNT</span><h2>{{ $user->name }}</h2><p>{{ $user->email }}</p><span class="badge">{{ $user->role }}</span><span class="badge status">{{ $user->status }}</span></div>
    @if($user->isCoach())<div class="summary-action"><span class="meta">PROFILE</span>@if($coach)<h2>{{ $coach->name }}</h2><p>審査状態: {{ $coach->status }}</p><div class="page-actions"><a class="btn secondary" href="{{ route('coaches.show',$coach) }}">プロフィール表示</a><a class="btn" href="{{ route('coaches.create') }}">編集</a></div>@else<h2>プロフィール未登録</h2><p>応募にはプロフィール登録と運営承認が必要です。</p><a class="btn" href="{{ route('coaches.create') }}">登録する</a>@endif</div>@endif
    @if($user->isOrganization())<div class="summary-action"><span class="meta">ORGANIZATION</span>@if($organization)<h2>{{ $organization->name }}</h2><p>審査状態: {{ $organization->status }}</p><div class="page-actions"><a class="btn secondary" href="{{ route('organizations.show',$organization) }}">団体表示</a><a class="btn secondary" href="{{ route('organizations.create') }}">編集</a>@if($organization->isApproved())<a class="btn" href="{{ route('jobs.create') }}">案件登録</a>@endif</div>@else<h2>団体未登録</h2><p>案件掲載には団体プロフィール登録が必要です。</p><a class="btn" href="{{ route('organizations.create') }}">登録する</a>@endif</div>@endif
</section>
@if($user->isCoach())
<section class="workspace-section"><div class="section-heading"><div><div class="eyebrow">APPLICATIONS</div><h2>応募・選考状況</h2></div><a href="{{ route('jobs.index') }}">案件を探す →</a></div>
@forelse($applications as $app)
<article class="application-card" id="application-{{ $app->id }}"><div class="application-main"><span class="badge status">{{ config('matching.application_statuses.'.$app->status,$app->status) }}</span><h3><a href="{{ route('jobs.show',$app->job) }}">{{ $app->job->title }}</a></h3><p>{{ $app->job->organization->name }}</p><p class="meta">応募日: {{ $app->created_at->format('Y/m/d') }}</p>@if(in_array($app->status,['accepted','completed']))<div class="contact-box"><strong>団体連絡先</strong><p>{{ $app->job->organization->manager_email }} / {{ $app->job->organization->manager_phone }}</p></div>@endif @unless(in_array($app->status,['rejected','withdrawn','completed','canceled']))<form method="post" action="{{ route('applications.update',$app) }}" onsubmit="return confirm('この応募を辞退しますか？')">@csrf @method('PATCH')<input type="hidden" name="status" value="withdrawn"><button class="btn secondary" type="submit">応募を辞退する</button></form>@endunless</div><ol class="status-timeline">@foreach($app->statusHistories as $history)<li><strong>{{ config('matching.application_statuses.'.$history->to_status,$history->to_status) }}</strong><span>{{ $history->created_at->format('Y/m/d H:i') }}@if($history->note) / {{ $history->note }}@endif</span></li>@endforeach</ol></article>
@empty<div class="empty-state">まだ応募はありません。</div>@endforelse
</section>
@endif
@if($user->isOrganization())
<section class="workspace-section"><div class="section-heading"><div><div class="eyebrow">RECRUITING</div><h2>掲載案件と応募者</h2></div>@if($organization && $organization->isApproved())<a href="{{ route('jobs.create') }}">新しい案件を登録 →</a>@endif</div>
@forelse($jobs as $job)
<article class="job-workspace"><div class="job-workspace-head"><div><span class="badge status">{{ $job->status }}</span><h3><a href="{{ route('jobs.show',$job) }}">{{ $job->title }}</a></h3></div><div class="applicant-count">{{ $job->applications->count() }}<small>応募</small></div></div>
@forelse($job->applications as $app)<div class="applicant" id="application-{{ $app->id }}"><div><a href="{{ route('coaches.show',$app->coachProfile) }}"><strong>{{ $app->coachProfile->name }}</strong></a><p class="meta">{{ $app->message }}</p>@if(in_array($app->status,['accepted','completed']))<div class="contact-box"><strong>指導者連絡先</strong><p>{{ $app->coachProfile->email }} / {{ $app->coachProfile->phone }}</p></div>@endif @if($app->status==='completed' && !$app->review)<form class="mini-review" method="post" action="{{ route('reviews.store',$app) }}">@csrf<select class="field" name="rating"><option value="5">★★★★★</option><option value="4">★★★★☆</option><option value="3">★★★☆☆</option></select><input class="field" name="title" placeholder="評価タイトル" required><textarea class="field" name="body" placeholder="指導の評価" required></textarea><button class="btn">評価を公開</button></form>@endif</div><form method="post" action="{{ route('applications.update',$app) }}">@csrf @method('PATCH')<select class="field" name="status">@foreach(config('matching.application_statuses') as $value => $label)@unless($value === 'withdrawn')<option value="{{ $value }}" @selected($app->status === $value)>{{ $label }}</option>@endunless @endforeach</select><input class="field" name="note" placeholder="理由・面談予定など"><button class="btn" type="submit">更新</button></form><ol class="status-timeline compact">@foreach($app->statusHistories as $history)<li><strong>{{ config('matching.application_statuses.'.$history->to_status,$history->to_status) }}</strong><span>{{ $history->created_at->format('m/d H:i') }}</span></li>@endforeach</ol></div>@empty<div class="empty-state compact">応募者はまだいません。</div>@endforelse
</article>
@empty<div class="empty-state">掲載案件はありません。</div>@endforelse
</section>
@endif
<section class="workspace-section"><div class="section-heading"><div><div class="eyebrow">SMART MATCHING</div><h2>{{ $user->isCoach() ? 'あなたにおすすめの案件' : '条件に合う指導者' }}</h2>@if($recommendationContext)<p class="meta">「{{ $recommendationContext->title }}」との条件一致度</p>@endif</div></div><div class="result-grid">@foreach($recommendations as $item)<article class="result-card"><div class="result-card-body"><div class="match-score">{{ $item->match_score }}<small>% MATCH</small></div>@if($user->isCoach())<h3><a href="{{ route('jobs.show',$item) }}">{{ $item->title }}</a></h3><p>{{ $item->organization->name }}</p><p class="meta">{{ $item->prefecture }} / {{ $item->sport }}</p>@else<h3><a href="{{ route('coaches.show',$item) }}">{{ $item->name }}</a></h3><p>{{ implode(' / ',(array)$item->fields) }}</p><p class="meta">{{ $item->main_prefecture }} / 充実度 {{ $item->completeness_score }}%</p>@endif</div></article>@endforeach</div></section>
<section class="workspace-section"><div class="section-heading"><div><div class="eyebrow">RECENT OFFERS</div><h2>オファー</h2></div><a href="{{ route('offers.index') }}">すべて見る →</a></div><div class="recent-offer-list">@forelse($offers as $offer)<a class="recent-offer-card" href="{{ route('offers.index') }}"><div class="recent-offer-status"><span>STATUS</span><strong>{{ config('matching.offer_statuses.'.$offer->status,$offer->status) }}</strong></div><div class="recent-offer-copy"><span>{{ $user->isCoach() ? 'FROM ORGANIZATION' : 'TO COACH' }}</span><h3>{{ $offer->subject }}</h3><p>{{ $user->isCoach() ? $offer->organization->name : $offer->coachProfile->name }} <time>{{ $offer->created_at->format('Y.m.d') }}</time></p></div><span class="recent-offer-arrow" aria-hidden="true">→</span></a>@empty<div class="empty-state">オファーはまだありません。</div>@endforelse</div></section>
@if($user->isOrganization() && $favoriteCoaches->count())<section class="workspace-section"><div class="section-heading"><div><div class="eyebrow">SAVED COACHES</div><h2>関心指導者</h2></div></div><div class="result-grid">@foreach($favoriteCoaches as $item)<article class="result-card"><div class="result-card-body"><h3><a href="{{ route('coaches.show',$item) }}">{{ $item->name }}</a></h3><p>{{ implode(' / ',(array)$item->fields) }}</p><a class="btn secondary" href="{{ route('offers.create',$item) }}">オファーする</a></div></article>@endforeach</div></section>@endif
@endsection
