<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminArticleController;
use App\Http\Controllers\AdminManagementController;
use App\Http\Controllers\AdminExportController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CoachController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\InquiryController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\PasswordResetController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\MatchingMasterController;
use App\Http\Controllers\VerificationDocumentController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/coaches', [CoachController::class, 'index'])->name('coaches.index');
Route::get('/organizations', [OrganizationController::class, 'index'])->name('organizations.index');
Route::get('/jobs', [JobController::class, 'index'])->name('jobs.index');
Route::get('/articles', [ArticleController::class, 'index'])->name('articles.index');
Route::get('/articles/{article}', [ArticleController::class, 'show'])->name('articles.show');

Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login']);
Route::get('/register', [AuthController::class, 'showRegister'])->name('register');
Route::post('/register', [AuthController::class, 'register']);
Route::get('/forgot-password', [PasswordResetController::class, 'requestForm'])->name('password.request');
Route::post('/forgot-password', [PasswordResetController::class, 'send'])->name('password.email');
Route::get('/reset-password/{token}', [PasswordResetController::class, 'resetForm'])->name('password.reset');
Route::post('/reset-password', [PasswordResetController::class, 'reset'])->name('password.update');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/admin', DashboardController::class)->middleware('admin')->name('admin.dashboard');
    Route::get('/coaches/create', [CoachController::class, 'create'])->name('coaches.create');
    Route::post('/coaches', [CoachController::class, 'store'])->name('coaches.store');
    Route::get('/organizations/create', [OrganizationController::class, 'create'])->name('organizations.create');
    Route::post('/organizations', [OrganizationController::class, 'store'])->name('organizations.store');
    Route::get('/jobs/create', [JobController::class, 'create'])->name('jobs.create');
    Route::post('/jobs', [JobController::class, 'store'])->name('jobs.store');
    Route::get('/jobs/{job}/edit', [JobController::class, 'edit'])->name('jobs.edit');
    Route::patch('/jobs/{job}', [JobController::class, 'update'])->name('jobs.update');
    Route::post('/jobs/{job}/applications', [ApplicationController::class, 'store'])->name('applications.store');
    Route::patch('/applications/{application}', [ApplicationController::class, 'update'])->name('applications.update');
    Route::post('/applications/{application}/review', [ReviewController::class, 'store'])->name('reviews.store');
    Route::get('/offers', [OfferController::class, 'index'])->name('offers.index');
    Route::get('/coaches/{coach}/offer', [OfferController::class, 'create'])->name('offers.create');
    Route::post('/coaches/{coach}/offer', [OfferController::class, 'store'])->name('offers.store');
    Route::patch('/offers/{offer}', [OfferController::class, 'update'])->name('offers.update');
    Route::post('/coaches/{coach}/favorite', [FavoriteController::class, 'toggle'])->name('favorites.toggle');
    Route::get('/coaches/{coach}/documents/{type}', [VerificationDocumentController::class, 'download'])->name('coaches.documents.download');
    Route::get('/inquiries', [InquiryController::class, 'index'])->name('inquiries.index');
    Route::get('/inquiries/create', [InquiryController::class, 'create'])->name('inquiries.create');
    Route::post('/inquiries', [InquiryController::class, 'store'])->name('inquiries.store');
    Route::get('/inquiries/{inquiry}', [InquiryController::class, 'show'])->name('inquiries.show');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::get('/notifications/{notification}', [NotificationController::class, 'read'])->name('notifications.read');
    Route::middleware('admin')->group(function () {
        Route::get('/admin/users', [AdminManagementController::class, 'users'])->name('admin.users.index');
        Route::get('/admin/coaches', [AdminManagementController::class, 'coaches'])->name('admin.coaches.index');
        Route::get('/admin/organizations', [AdminManagementController::class, 'organizations'])->name('admin.organizations.index');
        Route::get('/admin/jobs', [AdminManagementController::class, 'jobs'])->name('admin.jobs.index');
        Route::get('/admin/applications', [AdminManagementController::class, 'applications'])->name('admin.applications.index');
        Route::get('/admin/inquiries', [InquiryController::class, 'adminIndex'])->name('admin.inquiries.index');
        Route::get('/admin/offers', [AdminManagementController::class, 'offers'])->name('admin.offers.index');
        Route::get('/admin/reviews', [AdminManagementController::class, 'reviews'])->name('admin.reviews.index');
        Route::get('/admin/inquiries/{inquiry}', [InquiryController::class, 'show'])->name('admin.inquiries.show');
        Route::patch('/admin/inquiries/{inquiry}', [InquiryController::class, 'reply'])->name('admin.inquiries.reply');
        Route::get('/admin/export/{resource}', AdminExportController::class)->name('admin.export');
        Route::resource('/admin/articles', AdminArticleController::class)->except(['show', 'destroy'])->names('admin.articles');
        Route::get('/admin/masters', [MatchingMasterController::class, 'index'])->name('admin.masters.index');
        Route::post('/admin/masters', [MatchingMasterController::class, 'store'])->name('admin.masters.store');
        Route::patch('/admin/masters/{master}', [MatchingMasterController::class, 'update'])->name('admin.masters.update');
        Route::post('/admin/users/{user}/approve', [AdminController::class, 'approveUser'])->name('admin.users.approve');
        Route::post('/admin/coaches/{coach}/approve', [AdminController::class, 'approveCoach'])->name('admin.coaches.approve');
        Route::post('/admin/organizations/{organization}/approve', [AdminController::class, 'approveOrganization'])->name('admin.organizations.approve');
        Route::post('/admin/jobs/{job}/approve', [AdminController::class, 'approveJob'])->name('admin.jobs.approve');
        Route::patch('/admin/users/{user}/status', [AdminController::class, 'updateUserStatus'])->name('admin.users.status');
        Route::patch('/admin/coaches/{coach}/status', [AdminController::class, 'updateCoachStatus'])->name('admin.coaches.status');
        Route::patch('/admin/organizations/{organization}/status', [AdminController::class, 'updateOrganizationStatus'])->name('admin.organizations.status');
        Route::patch('/admin/jobs/{job}/status', [AdminController::class, 'updateJobStatus'])->name('admin.jobs.status');
        Route::patch('/admin/coaches/{coach}/verify', [AdminController::class, 'verifyCoach'])->name('admin.coaches.verify');
        Route::patch('/admin/reviews/{review}/status', [AdminController::class, 'updateReviewStatus'])->name('admin.reviews.status');
    });
});

Route::get('/coaches/{coach}', [CoachController::class, 'show'])->name('coaches.show');
Route::get('/organizations/{organization}', [OrganizationController::class, 'show'])->name('organizations.show');
Route::get('/jobs/{job}', [JobController::class, 'show'])->name('jobs.show');
