@extends('layouts.user')
@section('content')
<div class="page-heading"><div><div class="eyebrow">COACH DIRECTORY</div><h1>指導者を探す</h1></div><p class="result-count"><strong>{{ number_format($coaches->total()) }}</strong> 名</p></div>
<form class="form search-filter" method="get" action="{{ route('coaches.index') }}">
    <div class="grid3"><select class="field" name="prefecture"><option value="">都道府県・対応地域</option>@foreach($prefectures as $pref)<option value="{{ $pref }}" @selected(request('prefecture')===$pref)>{{ $pref }}</option>@endforeach</select><select class="field" name="field"><option value="">専門項目</option>@foreach($fields as $field)<option value="{{ $field }}" @selected(request('field')===$field)>{{ $field }}</option>@endforeach</select><input class="field" name="sport" value="{{ request('sport') }}" placeholder="競技"></div>
    <div class="grid3"><input class="field" name="area" value="{{ request('area') }}" placeholder="市区町村・エリア"><input class="field" name="keyword" value="{{ request('keyword') }}" placeholder="資格・実績・キーワード"><select class="field" name="sort"><option value="">更新順</option><option value="rating" @selected(request('sort')==='rating')>評価順</option><option value="complete" @selected(request('sort')==='complete')>プロフィール充実順</option></select></div>
    <div class="filter-footer"><label class="inline-check"><input type="checkbox" name="verified" value="1" @checked(request('verified'))> 本人・資格確認済みのみ</label><div class="page-actions"><select class="field compact-field" name="per_page"><option value="10">10件</option><option value="20" @selected(request('per_page')==20)>20件</option><option value="50" @selected(request('per_page')==50)>50件</option></select><button class="btn dark" type="submit">条件を絞り込む</button></div></div>
</form>
<div class="result-grid coach-results">
@forelse($coaches as $coach)
    @php($photo = $coach->photo_path ? (str_starts_with($coach->photo_path,'images/') ? asset($coach->photo_path) : asset('storage/'.$coach->photo_path)) : asset($loop->even ? 'images/coach-female-editorial.png' : 'images/sample-coach-profile.png'))
    <article class="result-card coach-card"><a class="result-image" href="{{ route('coaches.show',$coach) }}"><img src="{{ $photo }}" alt="{{ $coach->name }}"><span class="entity-image-label">COACH PROFILE</span></a><div class="result-card-body"><div class="page-actions"><span class="badge status">{{ $coach->verification_status === 'verified' ? '確認済み' : '公開中' }}</span><span class="badge">{{ $coach->main_prefecture }}</span></div><h2><a href="{{ route('coaches.show',$coach) }}">{{ $coach->name }}</a></h2><p class="rating">★ {{ $coach->reviews_avg_rating ? number_format($coach->reviews_avg_rating,1) : 'NEW' }} <small>({{ $coach->reviews_count }}件)</small></p><p>{{ Str::limit($coach->message,90) }}</p><p>@foreach((array)$coach->fields as $field)<span class="badge">{{ $field }}</span>@endforeach</p><p class="meta">{{ implode(' / ',(array)$coach->sports) }} / 希望額: 応相談</p><a class="entity-card-link" href="{{ route('coaches.show',$coach) }}">プロフィールを見る <span>→</span></a></div></article>
@empty<div class="empty-state">条件に合う指導者がまだ登録されていません。</div>@endforelse
</div>{{ $coaches->links() }}
<section class="wide-cta"><div><div class="eyebrow">BECOME A COACH</div><h2>あなたの専門性を、地域の力に。</h2><p>競技指導、トレーニング、メンタル、栄養、分析など、多様な専門家を募集しています。</p></div><a class="btn" href="{{ route('register') }}">指導者として登録</a></section>
@endsection
