@extends('layouts.user')
@section('content')
@php($photo = $coach->photo_path ? (str_starts_with($coach->photo_path,'images/') ? asset($coach->photo_path) : asset('storage/'.$coach->photo_path)) : asset('images/sample-coach-profile.png'))
<section class="detail-hero profile-detail-hero">
    <div class="detail-hero-media"><img src="{{ $photo }}" alt="{{ $coach->name }}"></div>
    <div class="detail-hero-content"><div class="eyebrow">VERIFIED COACH</div><div class="detail-badges"><span class="badge status">本人・資格確認済み</span><span class="badge">{{ $coach->main_prefecture }}</span></div><h1>{{ $coach->name }}</h1><p class="detail-subtitle">{{ $coach->kana }} @if($coach->roman_name)<span>/ {{ $coach->roman_name }}</span>@endif</p><p class="detail-message">{{ $coach->message }}</p><div class="hero-metrics"><div><strong>{{ $coach->reviewAverage() ?: 'NEW' }}</strong><span>評価</span></div><div><strong>{{ $coach->reviews()->count() }}</strong><span>レビュー</span></div><div><strong>{{ $coach->completeness_score }}%</strong><span>プロフィール充実度</span></div></div></div>
</section>
<div class="detail-actionbar"><div><span>専門分野</span><strong>{{ implode(' / ',(array)$coach->fields) }}</strong></div><div><span>対応競技</span><strong>{{ implode(' / ',(array)$coach->sports) }}</strong></div><div class="detail-actions">@auth @if(auth()->user()->isOrganization() && auth()->user()->organization)<form method="post" action="{{ route('favorites.toggle',$coach) }}">@csrf<button class="btn secondary" type="submit">保存する</button></form><a class="btn" href="{{ route('offers.create',$coach) }}">直接オファー</a>@else<a class="btn secondary" href="{{ route('inquiries.create',['coach'=>$coach->id]) }}">相談する</a>@endif @else<a class="btn" href="{{ route('register') }}">無料登録して詳しく見る</a>@endauth</div></div>
<section class="detail-layout"><div class="detail-main"><section class="detail-section"><div class="detail-section-title"><span>01</span><div><div class="eyebrow">PROFILE</div><h2>基本情報</h2></div></div><dl class="detail-definition"><div><dt>所属</dt><dd>{{ $coach->affiliation ?: '未設定' }}</dd></div><div><dt>学位</dt><dd>{{ $coach->degree ?: '未設定' }}</dd></div><div><dt>活動地域</dt><dd>{{ $coach->main_prefecture }} {{ $coach->area }}</dd></div>@if($coach->show_available_prefectures && count($coach->available_prefectures ?? []))<div><dt>対応可能地域</dt><dd>{{ implode(' / ',$coach->available_prefectures) }}</dd></div>@endif<div><dt>希望額</dt><dd>応相談</dd></div></dl></section>
@guest<section class="locked-content"><div><div class="eyebrow">MEMBERS ONLY</div><h2>実績・評価は会員限定です</h2><p>無料会員登録後、詳しい指導実績や団体からの評価を確認できます。</p><div class="page-actions"><a class="btn" href="{{ route('register') }}">無料会員登録</a><a class="btn secondary" href="{{ route('login') }}">ログイン</a></div></div></section>
@else<section class="detail-section"><div class="detail-section-title"><span>02</span><div><div class="eyebrow">EXPERIENCE</div><h2>指導実績とメッセージ</h2></div></div><div class="editorial-copy"><h3>指導への想い</h3><p class="preline">{{ $coach->message }}</p><h3>主な実績</h3><p class="preline">{{ $coach->achievements }}</p>@if($coach->show_request_history && $coach->request_history)<h3>依頼実績</h3><p class="preline">{{ $coach->request_history }}</p>@endif</div></section>@endguest</div>
<aside class="detail-aside"><div class="aside-block"><span>EXPERTISE</span><h2>専門性</h2><dl><div><dt>競技</dt><dd>{{ implode(' / ',(array)$coach->sports) }}</dd></div><div><dt>分野</dt><dd>{{ implode(' / ',(array)$coach->fields) }}</dd></div><div><dt>資格</dt><dd>{{ $coach->qualifications }}</dd></div><div><dt>キーワード</dt><dd>{{ $coach->keywords }}</dd></div></dl><p class="aside-updated">最終更新 {{ optional($coach->profile_updated_at)->format('Y.m.d') }}</p></div></aside></section>
@auth<section class="workspace-section"><div class="section-heading"><div><div class="eyebrow">REVIEWS</div><h2>団体からの評価</h2></div><span class="section-count">{{ $coach->reviews()->count() }}</span></div><div class="review-grid">@forelse($coach->reviews()->with('organization')->latest()->get() as $review)<article class="card review-card"><p class="rating">{{ str_repeat('★',$review->rating) }}{{ str_repeat('☆',5-$review->rating) }}</p><h3>{{ $review->title }}</h3><p>{{ $review->body }}</p><p class="meta">{{ $review->organization->name }} / {{ $review->created_at->format('Y.m.d') }}</p></article>@empty<div class="empty-state">評価はまだありません。</div>@endforelse</div></section>@endauth
@if($relatedJobs->count())<section class="workspace-section related-section"><div class="section-heading"><div><div class="eyebrow">RECOMMENDED OPPORTUNITIES</div><h2>この指導者に関連する案件</h2></div><a href="{{ route('jobs.index') }}">すべての案件を見る</a></div><div class="result-grid">@foreach($relatedJobs as $item)@php($jobImage=$item->image_path?(str_starts_with($item->image_path,'images/')?asset($item->image_path):asset('storage/'.$item->image_path)):asset('images/track-coaching.png'))<article class="result-card compact-result"><a class="result-image landscape" href="{{ route('jobs.show',$item) }}"><img src="{{ $jobImage }}" alt=""></a><div class="result-card-body"><span class="badge status">募集中</span><h3><a href="{{ route('jobs.show',$item) }}">{{ $item->title }}</a></h3><p class="meta">{{ $item->organization->name }} / {{ $item->prefecture }}</p></div></article>@endforeach</div></section>@endif
@include('partials.matching-promo',['title'=>'専門性を、必要としている地域へ。','text'=>'プロフィールを比較し、実績と資格を確認してから相談できます。団体からの直接オファーにも対応しています。'])
@endsection
