@extends('layouts.user')
@section('content')
@php($image=$job->image_path?(str_starts_with($job->image_path,'images/')?asset($job->image_path):asset('storage/'.$job->image_path)):asset('images/school-team-practice.png'))
<section class="detail-hero job-detail-hero"><div class="detail-hero-media"><img src="{{ $image }}" alt="{{ $job->title }}"></div><div class="detail-hero-content"><div class="eyebrow">OPEN OPPORTUNITY</div><div class="detail-badges"><span class="badge status">募集中</span><span class="badge">{{ $job->prefecture }}</span></div><h1>{{ $job->title }}</h1><p class="detail-subtitle"><a href="{{ route('organizations.show',$job->organization) }}">{{ $job->organization->name }}</a></p><p class="detail-message">{{ Str::limit($job->detail,140) }}</p><p class="detail-date">募集終了 {{ optional($job->publish_end_at)->format('Y.m.d') ?: '随時' }}</p></div></section>
<section class="fact-ribbon"><div><span>SPORT</span><strong>{{ $job->sport }}</strong></div><div><span>TARGET</span><strong>{{ $job->target_age }} / {{ $job->gender }}</strong></div><div><span>STYLE</span><strong>{{ $job->request_frequency }} / {{ $job->request_style }}</strong></div><div><span>FEE</span><strong>応相談</strong></div></section>
@guest<section class="locked-content"><div><div class="eyebrow">MEMBERS ONLY</div><h2>募集条件と応募機能は会員限定です</h2><p>無料会員登録後、必要資格、業務内容、応募フォームを確認できます。</p><div class="page-actions"><a class="btn" href="{{ route('register') }}">無料会員登録</a><a class="btn secondary" href="{{ route('login') }}">ログイン</a></div></div></section>
@else<section class="detail-layout job-detail-layout"><div class="detail-main"><section class="detail-section"><div class="detail-section-title"><span>01</span><div><div class="eyebrow">ROLE</div><h2>募集内容</h2></div></div><div class="editorial-copy"><h3>お願いしたい役割</h3><p class="preline">{{ $job->role_description }}</p><h3>希望詳細</h3><p class="preline">{{ $job->detail }}</p></div></section><section class="detail-section"><div class="detail-section-title"><span>02</span><div><div class="eyebrow">CONDITIONS</div><h2>応募条件</h2></div></div><div class="editorial-copy"><h3>必要な資格・経験</h3><p class="preline">{{ $job->required_conditions }}</p><h3>特記事項</h3><p class="preline">{{ $job->notes ?: '特になし' }}</p></div></section></div><aside class="detail-aside"><div class="aside-block"><span>ORGANIZATION</span><h2>{{ $job->organization->name }}</h2><p>{{ $job->organization->main_prefecture }} {{ $job->organization->area }}</p><a class="text-link" href="{{ route('organizations.show',$job->organization) }}">団体プロフィールを見る →</a><p class="aside-updated">案件更新 {{ $job->updated_at->format('Y.m.d') }}</p></div></aside></section>
@if(auth()->user()->isCoach() && auth()->user()->isApproved())<section class="application-panel"><div><div class="eyebrow">APPLICATION</div><h2>この案件に応募する</h2><p>応募後は団体がプロフィールとメッセージを確認します。</p></div><form method="post" action="{{ route('applications.store',$job) }}">@csrf<label><span class="label">応募メッセージ</span><textarea class="field textarea" name="message" required></textarea></label><div class="grid2"><label><span class="label">対応可能日時</span><textarea class="field textarea" name="available_schedule"></textarea></label><label><span class="label">希望条件補足</span><textarea class="field textarea" name="condition_note"></textarea></label></div><label><span class="label">添付資料URL</span><input class="field" name="attachment_url" type="url"></label><button class="btn">応募内容を確認して送信</button></form></section>@endif
@if(auth()->user()->isOrganization() && $job->organization->user_id===auth()->id())<div class="profile-bottom-cta"><a class="btn" href="{{ route('jobs.edit',$job) }}">案件を編集する</a></div>@endif @endguest
@if($relatedJobs->count())<section class="workspace-section related-section"><div class="section-heading"><div><div class="eyebrow">RELATED OPPORTUNITIES</div><h2>条件の近い案件</h2></div><a href="{{ route('jobs.index') }}">案件一覧へ</a></div><div class="result-grid">@foreach($relatedJobs as $item)@php($relatedImage=$item->image_path?(str_starts_with($item->image_path,'images/')?asset($item->image_path):asset('storage/'.$item->image_path)):asset('images/track-coaching.png'))<article class="result-card compact-result"><a class="result-image landscape" href="{{ route('jobs.show',$item) }}"><img src="{{ $relatedImage }}" alt=""></a><div class="result-card-body"><span class="badge status">募集中</span><h3><a href="{{ route('jobs.show',$item) }}">{{ $item->title }}</a></h3><p class="meta">{{ $item->organization->name }} / {{ $item->prefecture }}</p></div></article>@endforeach</div></section>@endif
@include('partials.matching-promo',['title'=>'部活動に、最適な専門性を。','text'=>'資格・指導実績を確認しながら比較できます。団体は気になる指導者へ直接オファーすることもできます。'])
@endsection
