@extends('layouts.user')
@section('content')
@php($image = $organization->image_path ? (str_starts_with($organization->image_path,'images/') ? asset($organization->image_path) : asset('storage/'.$organization->image_path)) : asset('images/school-team-practice.png'))
<section class="detail-hero organization-detail-hero"><div class="detail-hero-media"><img src="{{ $image }}" alt="{{ $organization->name }}"></div><div class="detail-hero-content"><div class="eyebrow">SPORTS COMMUNITY</div><div class="detail-badges"><span class="badge status">登録団体</span><span class="badge">{{ $organization->main_prefecture }}</span></div><h1>{{ $organization->name }}</h1><p class="detail-subtitle">{{ $organization->main_prefecture }} {{ $organization->area }}</p><p class="detail-message">{{ $organization->introduction ?: '地域に根ざしたスポーツ活動を行っています。' }}</p></div></section>
<section class="fact-ribbon organization-facts"><div><span>SPORT</span><strong>{{ $organization->sport }}</strong></div><div><span>TARGET</span><strong>{{ $organization->target_age }}</strong></div><div><span>MEMBERS</span><strong>{{ number_format($organization->member_count) }}名</strong></div><div><span>OPEN JOBS</span><strong>{{ $organization->jobs->count() }}件</strong></div></section>
<section class="detail-layout"><div class="detail-main"><section class="detail-section"><div class="detail-section-title"><span>01</span><div><div class="eyebrow">ABOUT</div><h2>団体について</h2></div></div><div class="editorial-copy"><p class="preline intro-copy">{{ $organization->introduction ?: '地域に根ざしたスポーツ活動を行っています。' }}</p>@if($organization->official_url)<a class="text-link" href="{{ $organization->official_url }}" target="_blank" rel="noopener">公式HP・SNSを見る →</a>@endif</div></section></div><aside class="detail-aside"><div class="aside-block"><span>ACTIVITY</span><h2>活動概要</h2><dl><div><dt>対象</dt><dd>{{ $organization->target_age }} / {{ $organization->gender }}</dd></div><div><dt>所属人数</dt><dd>{{ number_format($organization->member_count) }}名</dd></div><div><dt>活動地域</dt><dd>{{ $organization->main_prefecture }} {{ $organization->area }}</dd></div><div><dt>競技</dt><dd>{{ $organization->sport }}</dd></div></dl></div></aside></section>
<section class="workspace-section related-section"><div class="section-heading"><div><div class="eyebrow">OPEN OPPORTUNITIES</div><h2>この団体の募集案件</h2></div><span class="section-count">{{ $organization->jobs->count() }}</span></div><div class="result-grid">@forelse($organization->jobs as $job)@php($jobImage = $job->image_path ? (str_starts_with($job->image_path,'images/') ? asset($job->image_path) : asset('storage/'.$job->image_path)) : asset('images/track-coaching.png'))<article class="result-card compact-result"><a class="result-image landscape" href="{{ route('jobs.show',$job) }}"><img src="{{ $jobImage }}" alt="{{ $job->title }}"></a><div class="result-card-body"><span class="badge status">募集中</span><span class="badge">{{ $job->prefecture }}</span><h3><a href="{{ route('jobs.show',$job) }}">{{ $job->title }}</a></h3><p>{{ $job->sport }} / {{ $job->target_age }}</p><p class="meta">{{ $job->request_frequency }} / {{ $job->request_style }}</p></div></article>@empty<div class="empty-state">現在公開中の募集はありません。</div>@endforelse</div></section>
@include('partials.matching-promo',['title'=>'地域の活動に、新しい指導の選択肢を。','text'=>'学校、地域クラブ、自治体など多様な団体が利用できます。案件掲載から直接オファーまで、一つの場所で進められます。'])
@endsection
